<a href="https://colab.research.google.com/github/dave-howard/PyTorch/blob/main/00_pytorch_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## PyTorch start

# this is a text box in a notebook I think

In [2]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# thi tensor is just a single int '7'
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[1,2], [3,4]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
tensor([3, 4])


In [ ]:
TENSOR = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
print(TENSOR)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
TENSOR.shape

torch.Size([2, 2, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [3, 4]])

### Random Tensors

In [3]:
random_tensor = torch.rand(2, 2, 2)
random_tensor

tensor([[[0.7363, 0.5382],
         [0.3447, 0.6321]],

        [[0.5337, 0.0752],
         [0.8683, 0.8363]]])

In [ ]:
random_tensor.dtype

torch.float32

In [5]:
# represnt an image as x, y, rgb color values e.g.
random_image_tensor = torch.rand(224, 224, 3)  # x, y, color channel
random_image_tensor_via_size = torch.rand(size=(3, 3, 3))  # can optionally use 'size' parameter
print(random_image_tensor.shape)
print(random_image_tensor_via_size.shape)

torch.Size([224, 224, 3])
torch.Size([3, 3, 3])


### Zero's and Ones Tensor

In [ ]:
zeros = torch.zeros(2, 2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
ones = torch.ones(2, 2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# zeroes and ones can be used as masks - then multiply tensors
zeros * ones

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
# get type of values
ones.dtype

torch.float32

In [ ]:
torch.range(0, 10)

<ipython-input-38-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# prefer torch.arange()
tensor_range = torch.arange(0, 10)
tensor_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_range.dtype  # note these are int64, not float32 like tensor created via rand, ones, zeros

torch.int64