<a href="https://colab.research.google.com/github/dave-howard/PyTorch/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Create a random tensor with shape (7, 7).

In [2]:
t = torch.rand(7, 7)
t

tensor([[0.6771, 0.6437, 0.0843, 0.7566, 0.1384, 0.4843, 0.3655],
        [0.2865, 0.4903, 0.5472, 0.1984, 0.5829, 0.6936, 0.3564],
        [0.1936, 0.5898, 0.4907, 0.8787, 0.7554, 0.3174, 0.2363],
        [0.6021, 0.0911, 0.0048, 0.3376, 0.9671, 0.8771, 0.5789],
        [0.4942, 0.6087, 0.4681, 0.5928, 0.2025, 0.2510, 0.5836],
        [0.4638, 0.8036, 0.9768, 0.7730, 0.1415, 0.4306, 0.9431],
        [0.3332, 0.8791, 0.6626, 0.3788, 0.9929, 0.2360, 0.9407]])

In [11]:
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.6771, 0.6437, 0.0843, 0.7566, 0.1384, 0.4843, 0.3655],
         [0.2865, 0.4903, 0.5472, 0.1984, 0.5829, 0.6936, 0.3564],
         [0.1936, 0.5898, 0.4907, 0.8787, 0.7554, 0.3174, 0.2363],
         [0.6021, 0.0911, 0.0048, 0.3376, 0.9671, 0.8771, 0.5789],
         [0.4942, 0.6087, 0.4681, 0.5928, 0.2025, 0.2510, 0.5836],
         [0.4638, 0.8036, 0.9768, 0.7730, 0.1415, 0.4306, 0.9431],
         [0.3332, 0.8791, 0.6626, 0.3788, 0.9929, 0.2360, 0.9407]]),
 tensor([[0.4236, 0.8703, 0.4785, 0.4182, 0.7524, 0.0454, 0.9493]]),
 tensor([[0.4236],
         [0.8703],
         [0.4785],
         [0.4182],
         [0.7524],
         [0.0454],
         [0.9493]]),
 tensor([[1.6769],
         [1.7012],
         [2.0047],
         [1.7948],
         [1.9288],
         [2.7079],
         [3.0324]]))

In [12]:
torch.manual_seed(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4820],
         [0.8198],
         [0.9971],
         [0.6984],
         [0.5675],
         [0.8352],
         [0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [13]:
torch.manual_seed(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4820],
         [0.8198],
         [0.9971],
         [0.6984],
         [0.5675],
         [0.8352],
         [0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [ ]:
torch.manual_seed(0)
torch.cuda.seed_all(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)