<a href="https://colab.research.google.com/github/dave-howard/PyTorch/blob/main/00_pytorch_fundmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## PyTorch start

# this is a text box in a notebook I think

In [4]:
import torch
print(torch.__version__)

2.1.0+cu121


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# thi tensor is just a single int '7'
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([[1,2], [3,4]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
tensor([3, 4])


In [12]:
TENSOR = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
print(TENSOR)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [13]:
TENSOR.shape

torch.Size([2, 2, 2])

In [14]:
TENSOR[0]

tensor([[1, 2],
        [3, 4]])

### Random Tensors

In [15]:
random_tensor = torch.rand(2, 2, 2)
random_tensor

tensor([[[0.5454, 0.3417],
         [0.4615, 0.3475]],

        [[0.8659, 0.5576],
         [0.5468, 0.2414]]])

In [16]:
random_tensor.dtype

torch.float32

In [17]:
# represnt an image as x, y, rgb color values e.g.
random_image_tensor = torch.rand(224, 224, 3)  # x, y, color channel
random_image_tensor_via_size = torch.rand(size=(3, 3, 3))  # can optionally use 'size' parameter
print(random_image_tensor.shape)
print(random_image_tensor_via_size.shape)

torch.Size([224, 224, 3])
torch.Size([3, 3, 3])


### Zero's and Ones Tensor

In [18]:
zeros = torch.zeros(2, 2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [19]:
ones = torch.ones(2, 2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [20]:
# zeroes and ones can be used as masks - then multiply tensors
zeros * ones

tensor([[0., 0.],
        [0., 0.]])

In [21]:
# get type of values
ones.dtype

torch.float32

In [22]:
torch.range(0, 10)

<ipython-input-22-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# prefer torch.arange()
tensor_range = torch.arange(0, 10)
tensor_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
tensor_range.dtype  # note these are int64, not float32 like tensor created via rand, ones, zeros

torch.int64

In [25]:
to100 = torch.arange(0, 100, step=5)

In [26]:
[a for a in range(0, 100, 5)]

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [27]:
# tensors like - create tensor with same shape as another, with all zeroes
ten_zeros = torch.zeros_like(input=to100)
ten_zeros.size()

torch.Size([20])

## Tensor datatypes

In [28]:
fl32_tensor = torch.tensor([], dtype=torch.float32)
fl32_tensor.dtype

torch.float32

In [29]:
fl32_tensor.device

device(type='cpu')

## Tensor Operations

In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 1

tensor([2, 3, 4])

In [31]:
tensor + 3

tensor([4, 5, 6])

In [32]:
tensor * 2

tensor([2, 4, 6])

In [33]:
tensor -1

tensor([0, 1, 2])

In [34]:
tensor * tensor

tensor([1, 4, 9])

In [35]:
tensor + tensor

tensor([2, 4, 6])

## Matrix Multiplication

using `tensor.matmul(tensor1, tensor2)` or the rarer `tensor1 @ tensor2` syntax

### some rules

- inner dimensions must match i.e. [2, 2] x [2, 3] is ok [2, 2] x [3, 2] is NOT
- result shape will be based on outer dinemsions

In [36]:
tensor1 = torch.rand(4,2, dtype=torch.float64)
tensor2 = torch.rand(2,3, dtype=torch.float64)
tensor1, tensor2

(tensor([[0.4509, 0.3692],
         [0.3191, 0.2469],
         [0.6249, 0.1640],
         [0.0094, 0.9956]], dtype=torch.float64),
 tensor([[0.5598, 0.4860, 0.8689],
         [0.7013, 0.2997, 0.4652]], dtype=torch.float64))

In [37]:
torch.matmul(tensor1.type(torch.float32), tensor2.type(torch.float32)).shape  # expect [4, 3] output based on outer dimensions

torch.Size([4, 3])

In [38]:
torch.mm(tensor1.type(torch.float32), tensor2.type(torch.float32))  # mm is an alias for matmul

tensor([[0.5113, 0.3298, 0.5635],
        [0.3517, 0.2291, 0.3921],
        [0.4649, 0.3529, 0.6193],
        [0.7035, 0.3030, 0.4713]])

In [39]:
try:
  torch.matmul(tensor2, tensor1)  # this causes an error as inner dimensions do not match
  assert False  # does not get here
except RuntimeError as error:
  print(f'expected error:{type(error)} {error}')

expected error:<class 'RuntimeError'> mat1 and mat2 shapes cannot be multiplied (2x3 and 4x2)


### Transposing (2x3 to 3x2)

In [40]:
tensor2, tensor2.T

(tensor([[0.5598, 0.4860, 0.8689],
         [0.7013, 0.2997, 0.4652]], dtype=torch.float64),
 tensor([[0.5598, 0.7013],
         [0.4860, 0.2997],
         [0.8689, 0.4652]], dtype=torch.float64))

In [41]:
# convert a tensor to specific type
tensor2.type(torch.float16).dtype

torch.float16

## Aggregate methods - min, max, mean, avg etc

- each method has two aliases: torch.min(t) or t.min() where t is a tensor

In [42]:
tensor2.min(), torch.min(tensor2)

(tensor(0.2997, dtype=torch.float64), tensor(0.2997, dtype=torch.float64))

In [43]:
tensor2.max(), torch.max(tensor2)

(tensor(0.8689, dtype=torch.float64), tensor(0.8689, dtype=torch.float64))

In [44]:
tensor2.mean(), torch.mean(tensor2)

(tensor(0.5635, dtype=torch.float64), tensor(0.5635, dtype=torch.float64))

In [45]:
tensor2.sum(), torch.sum(tensor2)

(tensor(3.3810, dtype=torch.float64), tensor(3.3810, dtype=torch.float64))

In [46]:
tensor2.argmin(), tensor2.argmax()

(tensor(4), tensor(2))

In [47]:

tensor2[1]

tensor([0.7013, 0.2997, 0.4652], dtype=torch.float64)

## Reshaping, viewing, stacking, squeezing, and unqueezing

- view = a perspective on a tensor without creating a  new one
- stack = can be vertical or horizontal
- squeezing = removes all '1' dimensions from a tensor (???)
- permute - returns a view with dimensions swapped/permuted

In [48]:
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
x.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [50]:
z = x.view(1, 9)
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [51]:
z[:,0] = 10.0
z, x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [52]:
x

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [53]:
torch.stack([x, x, x], dim=1)

tensor([[10., 10., 10.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.]])

In [54]:
z

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [55]:
z.squeeze(), z  # remove the 'unnecessary' outer dimension

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]))

In [56]:
x = torch.zeros(2, 1, 2, 1, 2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [57]:
y = x.squeeze()
y.shape

torch.Size([2, 2, 2])

In [58]:
y = x.squeeze(0)  # dim 0 is not of size 1, so no effect
y.shape

torch.Size([2, 1, 2, 1, 2])

In [59]:
y = x.squeeze(1, 2, 3)  # dim's 1 and 3 are size 1, so these are removed
y.shape
# note: no effect on dim 2 as it is not of size 1

torch.Size([2, 2, 2])

In [60]:
y.unsqueeze(dim=1).shape, y.shape  # insert a new dimension at dim 0

(torch.Size([2, 1, 2, 2]), torch.Size([2, 2, 2]))

In [61]:
y.unsqueeze(dim=0).shape, y.shape  #same as dim 1

(torch.Size([1, 2, 2, 2]), torch.Size([2, 2, 2]))

In [62]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [63]:
x.permute(1,3,0,2,4).shape  # re-order the dimensions of a tensor

torch.Size([1, 1, 2, 2, 2])

In [64]:
img = torch.rand(8, 8, 3)  # a very small image 8x8 with RGB
img.permute(2, 0, 1)

tensor([[[0.5910, 0.5918, 0.4302, 0.3310, 0.3129, 0.8569, 0.0705, 0.8234],
         [0.2101, 0.5420, 0.2089, 0.9374, 0.3595, 0.3467, 0.0240, 0.0086],
         [0.9458, 0.1113, 0.4778, 0.6395, 0.3698, 0.1868, 0.5171, 0.4313],
         [0.3580, 0.1759, 0.3956, 0.6821, 0.2338, 0.7532, 0.1798, 0.3625],
         [0.3498, 0.8186, 0.6749, 0.5640, 0.3783, 0.8658, 0.8607, 0.6466],
         [0.1639, 0.9764, 0.0434, 0.0538, 0.8287, 0.1731, 0.0338, 0.5727],
         [0.7025, 0.8528, 0.4827, 0.3442, 0.3389, 0.4443, 0.9020, 0.1823],
         [0.3099, 0.0516, 0.3458, 0.8303, 0.3366, 0.8088, 0.0758, 0.1269]],

        [[0.0996, 0.1276, 0.8556, 0.7254, 0.8657, 0.8450, 0.1014, 0.9431],
         [0.4270, 0.6575, 0.4491, 0.1172, 0.6034, 0.9710, 0.3315, 0.6740],
         [0.8304, 0.6605, 0.2375, 0.8114, 0.2799, 0.7039, 0.3193, 0.7222],
         [0.4793, 0.7311, 0.7085, 0.1568, 0.1956, 0.7836, 0.2124, 0.0592],
         [0.8975, 0.1384, 0.2884, 0.8151, 0.0072, 0.3729, 0.0988, 0.2963],
         [0.7099, 0.025

## Indexing

PyTorch is similar to Numpy

In [65]:
x = torch.arange(1, 10).reshape(1, 3, 3)  # convert 1->9 to 1 x 3 x 3
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
x[0][0], x[0, 0]  # the same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [68]:
x[0][0][0], x[0, 0, 0]  # the same

(tensor(1), tensor(1))

In [69]:
x[:, :, 1], x[:][:][0]  # get a column - only works for first syntax

(tensor([[2, 5, 8]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [70]:
import numpy as np
import torch

In [71]:
np.__version__

'1.23.5'

In [72]:
array = np.arange(1.0, 9.0)

In [73]:
# create a tensor from numpy array - inherits type from numpy array
array, torch.from_numpy(array), array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 dtype('float64'))

In [74]:
t = torch.ones(5)
t, t.numpy()

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

Reproducability (rand but not random)

In [75]:
#r1 = torch.rand(2, 2)
#r2 = torch.rand(2, 2)
#r1 == r2  # these are VERY unlikely to be equal

In [76]:
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(RANDOM_SEED)
r1 = torch.rand(2, 2)
torch.manual_seed(RANDOM_SEED)
r2 = torch.rand(2, 2)

r1, r2, r1 == r2  # these should be equal

(tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[True, True],
         [True, True]]))

In [77]:
!nvidia-smi

Wed Dec 20 20:37:22 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [78]:
torch.cuda.is_available()

True

In [79]:
torch.cuda.device_count()

1

In [82]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
t = torch.tensor([1,2,3])
t, t.device

(tensor([1, 2, 3]), device(type='cpu'))

In [84]:
t_on_gpu = t.to(device)
t_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [86]:
t_on_cpu = t.to('cpu')  # i.e. if we want to use NumPy which only supports CPU
t_on_cpu, t_on_cpu.numpy()

(tensor([1, 2, 3]), array([1, 2, 3]))