<a href="https://colab.research.google.com/github/dave-howard/PyTorch/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

Create a random tensor with shape (7, 7).

In [3]:
t = torch.rand(7, 7)
t

tensor([[0.4464, 0.7262, 0.7978, 0.5282, 0.5291, 0.0395, 0.4445],
        [0.7007, 0.1409, 0.5229, 0.8175, 0.5169, 0.7479, 0.1127],
        [0.9831, 0.5576, 0.0797, 0.2035, 0.3374, 0.4936, 0.8173],
        [0.9805, 0.0589, 0.5888, 0.0545, 0.7712, 0.8692, 0.7501],
        [0.0249, 0.8778, 0.1847, 0.8977, 0.5147, 0.2224, 0.1602],
        [0.9980, 0.6186, 0.3691, 0.0829, 0.0463, 0.9409, 0.1528],
        [0.6104, 0.5196, 0.1571, 0.7471, 0.8060, 0.0117, 0.4592]])

In [4]:
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.4464, 0.7262, 0.7978, 0.5282, 0.5291, 0.0395, 0.4445],
         [0.7007, 0.1409, 0.5229, 0.8175, 0.5169, 0.7479, 0.1127],
         [0.9831, 0.5576, 0.0797, 0.2035, 0.3374, 0.4936, 0.8173],
         [0.9805, 0.0589, 0.5888, 0.0545, 0.7712, 0.8692, 0.7501],
         [0.0249, 0.8778, 0.1847, 0.8977, 0.5147, 0.2224, 0.1602],
         [0.9980, 0.6186, 0.3691, 0.0829, 0.0463, 0.9409, 0.1528],
         [0.6104, 0.5196, 0.1571, 0.7471, 0.8060, 0.0117, 0.4592]]),
 tensor([[0.2401, 0.6997, 0.3215, 0.9774, 0.0588, 0.5581, 0.2819]]),
 tensor([[0.2401],
         [0.6997],
         [0.3215],
         [0.9774],
         [0.0588],
         [0.5581],
         [0.2819]]),
 tensor([[1.5665],
         [1.7135],
         [1.3765],
         [1.2610],
         [1.7564],
         [1.4430],
         [1.4742]]))

In [5]:
torch.manual_seed(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4820],
         [0.8198],
         [0.9971],
         [0.6984],
         [0.5675],
         [0.8352],
         [0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [6]:
torch.manual_seed(0)
t = torch.rand(7, 7)
t2 = torch.rand(1, 7)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4820],
         [0.8198],
         [0.9971],
         [0.6984],
         [0.5675],
         [0.8352],
         [0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [11]:
torch.manual_seed(0)
torch.cuda.manual_seed_all(0)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
t = torch.rand(7, 7, device=device)
t2 = torch.rand(1, 7, device=device)
t3 = t2.transpose(1, 0)  # change order of dimensions
t, t2, t3, torch.mm(t, t3)

(tensor([[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967, 0.4150],
         [0.8203, 0.2290, 0.9096, 0.1183, 0.0752, 0.4092, 0.9601],
         [0.2093, 0.1940, 0.8909, 0.4387, 0.3570, 0.5454, 0.8299],
         [0.2099, 0.7684, 0.4290, 0.2117, 0.6606, 0.1654, 0.4250],
         [0.9927, 0.6964, 0.2472, 0.7028, 0.7494, 0.9303, 0.0494],
         [0.0750, 0.7223, 0.9478, 0.3647, 0.2215, 0.7784, 0.6391],
         [0.2077, 0.7045, 0.9609, 0.0594, 0.3358, 0.0616, 0.7030]],
        device='cuda:0'),
 tensor([[0.9722, 0.7910, 0.4690, 0.3300, 0.3345, 0.3783, 0.7640]],
        device='cuda:0'),
 tensor([[0.9722],
         [0.7910],
         [0.4690],
         [0.3300],
         [0.3345],
         [0.3783],
         [0.7640]], device='cuda:0'),
 tensor([[2.0534],
         [2.3578],
         [1.8793],
         [1.6912],
         [2.5042],
         [2.0659],
         [1.9022]], device='cuda:0'))

In [15]:
torch.manual_seed(1234)
rt1 = torch.rand(2, 3).to(device=device)
rt2 = torch.rand(2, 3).to(device=device)
rt1, rt2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [17]:
rt3 = rt2.transpose(1, 0)  # ready to matrix multiply
mm = torch.mm(rt1, rt3)
rt3, mm

(tensor([[0.0518, 0.3315],
         [0.4681, 0.7837],
         [0.6738, 0.5631]], device='cuda:0'),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))

In [18]:
mm.min(), mm.max()

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [19]:
mm.argmin(), mm.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [22]:
torch.manual_seed(7)
rt1 = torch.rand(1, 1, 1, 10)
rt2 = rt1.squeeze()
rt1.shape, rt2.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))